### ISSUE TITLE
Safari 및 WebKit 브라우저에서 모달이 보이지 않음

### ISSUE THREAD

**Issue by EATSTEAK** [Twinsteak/lockerweb#321]
- #145 에서 해결되었으나 #288 에서 다시 발생
- 현재 예약 진행을 위해 임시로 모달이 스크린 `height` 를 따라가도록 하여 해결
- WebKit의 dialog 구현이 이상해서 그런 듯 한데, 어캄?

**Comment by Twince** [comment]
사파리 webkit로 한번,, 수정해보죠 하핫
